name: Publish (Maven Central)
on: workflow_dispatch
jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Store Release Version
        run: |
          echo "RELEASE_VERSION=$(./scripts/print-release-version.sh)" >> $GITHUB_ENV
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: "maven"
      - name: Publish
        run: ./scripts/publish.sh -Ppublish --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          body: |
            This release can be obtained from Maven Central at https://repo1.maven.org/maven2/io/github/libzeal/zeal-assertion/${{ env.RELEASE_VERSION }}/.
            
            The `zeal-assertion` and `zeal-types-core` dependency can be added using the following: 
  
            ```
            <dependency>
                <groupId>io.github.libzeal</groupId>
                <artifactId>zeal-assertion</artifactId>
                <version>${{ env.RELEASE_VERSION }}</version>
            </dependency>
            <dependency>
                <groupId>io.github.libzeal</groupId>
                <artifactId>zeal-types-core</artifactId>
                <version>${{ env.RELEASE_VERSION }}</version>
            </dependency>
            ```
            
            ### Changelog for this Release
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
